// Generated by CoffeeScript 1.7.1
(function() {
  require({
    paths: {
      ember: '../vendor/ember/ember',
      handlebars: '../vendor/handlebars/handlebars',
      jquery: '../vendor/jquery/dist/jquery',
      templates: '../javascripts/templates'
    }
  }, ['jquery', 'handlebars', 'ember'], function() {
    var App;
    App = Ember.Application.create();
    App.Router.map(function() {});
    return App.IndexRoute = Ember.Route.extend({
      model: function() {
        return ['red', 'yellow', 'blue'];
      }
    });
  });

}).call(this);

//# sourceMappingURL=app.map
