// Generated by CoffeeScript 1.7.1
(function() {
  require({
    shim: {
      'planetaryjs': {
        exports: 'planetaryjs'
      },
      'setupRotatingGlobe': {
        deps: ['planetaryjs']
      }
    },
    paths: {
      ember: '../vendor/ember/ember',
      handlebars: '../vendor/handlebars/handlebars',
      jquery: '../vendor/jquery/dist/jquery',
      templates: '../javascripts/templates',
      planetaryjs: '../vendor/planetary.js/dist/planetaryjs',
      d3: '../vendor/d3/d3',
      topojson: '../vendor/topojson/topojson',
      setupRotatingGlobe: '../vendor/planetary.js/script/setup.rotating.globe',
      knob: '../vendor/jquery-knob/js/jquery.knob'
    }
  }, ['jquery', 'handlebars', 'ember', 'd3', 'knob'], function() {
    var App;
    App = Ember.Application.create();
    App.Router.map(function() {});
    return App.IndexRoute = Ember.Route.extend({
      model: function() {
        return ['red', 'yellow', 'blue'];
      },
      renderTemplate: function() {
        Ember.run.scheduleOnce('afterRender', this, 'setupGlobe');
        return this.render();
      },
      setupGlobe: function() {
        $(".dial").knob();
        return require(['setupRotatingGlobe']);

        /*
        setTimeout(->
           console.log('stuff')
           require 'setupRotatingGlobe'
        ,1500)
         */
      }
    });
  });

}).call(this);

//# sourceMappingURL=app.map
