// Generated by CoffeeScript 1.7.1
(function() {
  var connect, port, util;

  util = require('util');

  connect = require('connect');

  port = 1337;

  connect.createServer(connect["static"](__dirname + '/source')).listen(port);

  util.puts('Listening on ' + port + '...');

  util.puts('Press Ctrl + C to stop.');

}).call(this);

//# sourceMappingURL=server.map
